// Comprehensive, real ISO 4217 active-currency list (154 currencies),
// sourced from the ISO 4217 maintenance agency's public dataset via
// datahub.io/core/currency-codes (public domain, ODC-PDDL-1.0), not
// hand-typed - this avoids getting obscure currency codes/names wrong.
// Financial index units that don't actually circulate (Bolivia's Mvdol,
// Chile's Unidad de Fomento, Colombia's Unidad de Valor Real) are
// excluded, since nobody sends a remittance in those.
//
// `live: true` means Frankfurter (the app's real FX data source) has
// actual rate history for this currency - see marketService.js. The
// other ~124 are real, selectable currencies, but will show simulated
// rate data, clearly labeled as such, since no free rate feed covers
// them. This list intentionally includes all of them anyway - a user
// in Lagos or Karachi should be able to pick their own currency as a
// base, not just as a receiving corridor.
export const ALL_CURRENCIES = [
  { code: 'AFN', name: 'Afghan Afghani', live: false },
  { code: 'ALL', name: 'Albanian Lek', live: false },
  { code: 'DZD', name: 'Algerian Dinar', live: false },
  { code: 'AOA', name: 'Angolan Kwanza', live: false },
  { code: 'ARS', name: 'Argentine Peso', live: false },
  { code: 'AMD', name: 'Armenian Dram', live: false },
  { code: 'AWG', name: 'Aruban Florin', live: false },
  { code: 'AUD', name: 'Australian Dollar', live: true },
  { code: 'AZN', name: 'Azerbaijani Manat', live: false },
  { code: 'BSD', name: 'Bahamian Dollar', live: false },
  { code: 'BHD', name: 'Bahraini Dinar', live: false },
  { code: 'BDT', name: 'Bangladeshi Taka', live: false },
  { code: 'BBD', name: 'Barbadian Dollar', live: false },
  { code: 'BYN', name: 'Belarusian Ruble', live: false },
  { code: 'BZD', name: 'Belizean Dollar', live: false },
  { code: 'BMD', name: 'Bermudian Dollar', live: false },
  { code: 'BTN', name: 'Bhutanese Ngultrum', live: false },
  { code: 'BOB', name: 'Bolivian Boliviano', live: false },
  { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', live: false },
  { code: 'BWP', name: 'Botswana Pula', live: false },
  { code: 'BRL', name: 'Brazilian Real', live: true },
  { code: 'BND', name: 'Brunei Dollar', live: false },
  { code: 'BIF', name: 'Burundian Franc', live: false },
  { code: 'XPF', name: 'CFP Franc (Pacific)', live: false },
  { code: 'KHR', name: 'Cambodian Riel', live: false },
  { code: 'CAD', name: 'Canadian Dollar', live: true },
  { code: 'CVE', name: 'Cape Verdean Escudo', live: false },
  { code: 'XCG', name: 'Caribbean Guilder', live: false },
  { code: 'KYD', name: 'Cayman Islands Dollar', live: false },
  { code: 'XAF', name: 'Central African CFA Franc', live: false },
  { code: 'CLP', name: 'Chilean Peso', live: false },
  { code: 'CNY', name: 'Chinese Yuan', live: true },
  { code: 'COP', name: 'Colombian Peso', live: false },
  { code: 'KMF', name: 'Comorian Franc', live: false },
  { code: 'CDF', name: 'Congolese Franc', live: false },
  { code: 'CRC', name: 'Costa Rican Colón', live: false },
  { code: 'CUP', name: 'Cuban Peso', live: false },
  { code: 'CZK', name: 'Czech Koruna', live: true },
  { code: 'DKK', name: 'Danish Krone', live: true },
  { code: 'DJF', name: 'Djiboutian Franc', live: false },
  { code: 'DOP', name: 'Dominican Peso', live: false },
  { code: 'XCD', name: 'East Caribbean Dollar', live: false },
  { code: 'EGP', name: 'Egyptian Pound', live: false },
  { code: 'ERN', name: 'Eritrean Nakfa', live: false },
  { code: 'SZL', name: 'Eswatini Lilangeni', live: false },
  { code: 'ETB', name: 'Ethiopian Birr', live: false },
  { code: 'EUR', name: 'Euro', live: true },
  { code: 'FKP', name: 'Falkland Islands Pound', live: false },
  { code: 'FJD', name: 'Fiji Dollar', live: false },
  { code: 'GMD', name: 'Gambian Dalasi', live: false },
  { code: 'GEL', name: 'Georgian Lari', live: false },
  { code: 'GHS', name: 'Ghana Cedi', live: false },
  { code: 'GIP', name: 'Gibraltar Pound', live: false },
  { code: 'GTQ', name: 'Guatemalan Quetzal', live: false },
  { code: 'GNF', name: 'Guinean Franc', live: false },
  { code: 'GYD', name: 'Guyanese Dollar', live: false },
  { code: 'HTG', name: 'Haitian Gourde', live: false },
  { code: 'HNL', name: 'Honduran Lempira', live: false },
  { code: 'HKD', name: 'Hong Kong Dollar', live: true },
  { code: 'HUF', name: 'Hungarian Forint', live: true },
  { code: 'ISK', name: 'Icelandic Krona', live: true },
  { code: 'INR', name: 'Indian Rupee', live: true },
  { code: 'IDR', name: 'Indonesian Rupiah', live: true },
  { code: 'IRR', name: 'Iranian Rial', live: false },
  { code: 'IQD', name: 'Iraqi Dinar', live: false },
  { code: 'ILS', name: 'Israeli New Shekel', live: true },
  { code: 'JMD', name: 'Jamaican Dollar', live: false },
  { code: 'JPY', name: 'Japanese Yen', live: true },
  { code: 'JOD', name: 'Jordanian Dinar', live: false },
  { code: 'KZT', name: 'Kazakhstani Tenge', live: false },
  { code: 'KES', name: 'Kenyan Shilling', live: false },
  { code: 'KWD', name: 'Kuwaiti Dinar', live: false },
  { code: 'KGS', name: 'Kyrgyzstani Som', live: false },
  { code: 'LAK', name: 'Lao Kip', live: false },
  { code: 'LBP', name: 'Lebanese Pound', live: false },
  { code: 'LSL', name: 'Lesotho Loti', live: false },
  { code: 'LRD', name: 'Liberian Dollar', live: false },
  { code: 'LYD', name: 'Libyan Dinar', live: false },
  { code: 'MOP', name: 'Macanese Pataca', live: false },
  { code: 'MKD', name: 'Macedonian Denar', live: false },
  { code: 'MGA', name: 'Malagasy Ariary', live: false },
  { code: 'MWK', name: 'Malawian Kwacha', live: false },
  { code: 'MYR', name: 'Malaysian Ringgit', live: true },
  { code: 'MVR', name: 'Maldivian Rufiyaa', live: false },
  { code: 'MRU', name: 'Mauritanian Ouguiya', live: false },
  { code: 'MUR', name: 'Mauritian Rupee', live: false },
  { code: 'MXN', name: 'Mexican Peso', live: true },
  { code: 'MDL', name: 'Moldovan Leu', live: false },
  { code: 'MNT', name: 'Mongolian Tugrik', live: false },
  { code: 'MAD', name: 'Moroccan Dirham', live: false },
  { code: 'MZN', name: 'Mozambican Metical', live: false },
  { code: 'MMK', name: 'Myanmar Kyat', live: false },
  { code: 'NAD', name: 'Namibian Dollar', live: false },
  { code: 'NPR', name: 'Nepalese Rupee', live: false },
  { code: 'TWD', name: 'New Taiwan Dollar', live: false },
  { code: 'NZD', name: 'New Zealand Dollar', live: true },
  { code: 'NIO', name: 'Nicaraguan Córdoba', live: false },
  { code: 'NGN', name: 'Nigerian Naira', live: false },
  { code: 'KPW', name: 'North Korean Won', live: false },
  { code: 'NOK', name: 'Norwegian Krone', live: true },
  { code: 'PKR', name: 'Pakistani Rupee', live: false },
  { code: 'PAB', name: 'Panamanian Balboa', live: false },
  { code: 'PGK', name: 'Papua New Guinean Kina', live: false },
  { code: 'PYG', name: 'Paraguayan Guarani', live: false },
  { code: 'PEN', name: 'Peruvian Sol', live: false },
  { code: 'UYU', name: 'Peso Uruguayo', live: false },
  { code: 'PHP', name: 'Philippine Peso', live: true },
  { code: 'PLN', name: 'Polish Zloty', live: true },
  { code: 'GBP', name: 'Pound Sterling', live: true },
  { code: 'QAR', name: 'Qatari Rial', live: false },
  { code: 'OMR', name: 'Rial Omani', live: false },
  { code: 'RON', name: 'Romanian Leu', live: true },
  { code: 'RUB', name: 'Russian Ruble', live: false },
  { code: 'RWF', name: 'Rwandan Franc', live: false },
  { code: 'SHP', name: 'Saint Helena Pound', live: false },
  { code: 'SVC', name: 'Salvadoran Colón', live: false },
  { code: 'WST', name: 'Samoan Tala', live: false },
  { code: 'SAR', name: 'Saudi Riyal', live: false },
  { code: 'RSD', name: 'Serbian Dinar', live: false },
  { code: 'SCR', name: 'Seychellois Rupee', live: false },
  { code: 'SLE', name: 'Sierra Leonean Leone', live: false },
  { code: 'SGD', name: 'Singapore Dollar', live: true },
  { code: 'SBD', name: 'Solomon Islands Dollar', live: false },
  { code: 'SOS', name: 'Somali Shilling', live: false },
  { code: 'ZAR', name: 'South African Rand', live: true },
  { code: 'KRW', name: 'South Korean Won', live: true },
  { code: 'SSP', name: 'South Sudanese Pound', live: false },
  { code: 'LKR', name: 'Sri Lankan Rupee', live: false },
  { code: 'SDG', name: 'Sudanese Pound', live: false },
  { code: 'SRD', name: 'Surinam Dollar', live: false },
  { code: 'SEK', name: 'Swedish Krona', live: true },
  { code: 'CHF', name: 'Swiss Franc', live: true },
  { code: 'SYP', name: 'Syrian Pound', live: false },
  { code: 'STN', name: 'São Tomé and Príncipe Dobra', live: false },
  { code: 'TJS', name: 'Tajikistani Somoni', live: false },
  { code: 'TZS', name: 'Tanzanian Shilling', live: false },
  { code: 'THB', name: 'Thai Baht', live: true },
  { code: 'TOP', name: 'Tongan Paʻanga', live: false },
  { code: 'TTD', name: 'Trinidad and Tobago Dollar', live: false },
  { code: 'TND', name: 'Tunisian Dinar', live: false },
  { code: 'TRY', name: 'Turkish Lira', live: true },
  { code: 'TMT', name: 'Turkmenistani Manat', live: false },
  { code: 'AED', name: 'UAE Dirham', live: false },
  { code: 'USD', name: 'US Dollar', live: true },
  { code: 'UGX', name: 'Ugandan Shilling', live: false },
  { code: 'UAH', name: 'Ukrainian Hryvnia', live: false },
  { code: 'UZS', name: 'Uzbekistani Som', live: false },
  { code: 'VUV', name: 'Vanuatu Vatu', live: false },
  { code: 'VES', name: 'Venezuelan Bolívar', live: false },
  { code: 'VND', name: 'Vietnamese Dong', live: false },
  { code: 'XOF', name: 'West African CFA Franc', live: false },
  { code: 'YER', name: 'Yemeni Rial', live: false },
  { code: 'ZMW', name: 'Zambian Kwacha', live: false },
  { code: 'ZWG', name: 'Zimbabwe Gold', live: false },
];

export const CURRENCY_CODES = ALL_CURRENCIES.map((c) => c.code);

export function getCurrencyName(code) {
  return ALL_CURRENCIES.find((c) => c.code === code)?.name || code;
}

export function isLiveCurrency(code) {
  return !!ALL_CURRENCIES.find((c) => c.code === code)?.live;
}